'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    'OBSERVAÇÃO: Esse arquivo é gerado automaticamente; não o modifique diretamente.  Para fazer alterações,
    ' ou se você encontrar erros de compilação neste arquivo, vá para o Designer de Projeto
    ' (vá para Propriedades do Projeto ou clique duas vezes no nó Meu Projeto em
    ' Gerenciador de Soluções) e faça as alterações na guia Aplicativo.
    '
    Partial Friend Class MyApplication
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = false
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = true
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
        End Sub
        
        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>  _
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.Sistema_Cadymus.Frm_main
        End Sub
    End Class
End Namespace
